<a href="https://colab.research.google.com/github/ag22042008/data-Science-notebooks/blob/main/Titanicprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [95]:
df=sns.load_dataset('titanic')

In [96]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [97]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [98]:
df.info()#deck can be dropped as very large no of values


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [99]:
df.drop(["deck","embark_town","class","who","adult_male","alive"],axis=1,inplace=True)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [101]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [103]:
df.dropna(subset=['embarked'],inplace=True)

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [105]:
df = pd.get_dummies(df, columns=['embarked'])

In [106]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['sex']=le.fit_transform(df['sex'])

In [107]:
df['age']=df['age'].round(2)

In [108]:
df.head()

survived  pclass  sex   age  sibsp  parch     fare  alone  embarked_C  \
0         0       3    1  22.0      1      0   7.2500  False       False   
1         1       1    0  38.0      1      0  71.2833  False        True   
2         1       3    0  26.0      0      0   7.9250   True       False   
3         1       1    0  35.0      1      0  53.1000  False       False   
4         0       3    1  35.0      0      0   8.0500   True       False   

   embarked_Q  embarked_S  
0       False        True  
1       False       False  
2       False        True  
3       False        True  
4       False        True

In [109]:
df=df.astype(int)

In [110]:
df

survived  pclass  sex  age  sibsp  parch  fare  alone  embarked_C  \
0           0       3    1   22      1      0     7      0           0   
1           1       1    0   38      1      0    71      0           1   
2           1       3    0   26      0      0     7      1           0   
3           1       1    0   35      1      0    53      0           0   
4           0       3    1   35      0      0     8      1           0   
..        ...     ...  ...  ...    ...    ...   ...    ...         ...   
886         0       2    1   27      0      0    13      1           0   
887         1       1    0   19      0      0    30      1           0   
888         0       3    0   29      1      2    23      0           0   
889         1       1    1   26      0      0    30      1           1   
890         0       3    1   32      0      0     7      1           0   

     embarked_Q  embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[889 rows x 11 columns]

In [111]:
df.shape

(889, 11)

In [112]:
df2=df.copy()

In [113]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df2_scaled_array = scaler.fit_transform(df2)
df2 = pd.DataFrame(df2_scaled_array, columns=df.columns)

In [114]:
df2

survived    pclass       sex       age     sibsp     parch      fare  \
0   -0.786961  0.825209  0.735342 -0.578023  0.431350 -0.474326 -0.496733   
1    1.270711 -1.572211 -1.359911  0.655371  0.431350 -0.474326  0.791539   
2    1.270711  0.825209 -1.359911 -0.269675 -0.475199 -0.474326 -0.496733   
3    1.270711 -1.572211 -1.359911  0.424109  0.431350 -0.474326  0.429213   
4   -0.786961  0.825209  0.735342  0.424109 -0.475199 -0.474326 -0.476604   
..        ...       ...       ...       ...       ...       ...       ...   
884 -0.786961 -0.373501  0.735342 -0.192588 -0.475199 -0.474326 -0.375957   
885  1.270711 -1.572211 -1.359911 -0.809285 -0.475199 -0.474326 -0.033760   
886 -0.786961  0.825209 -1.359911 -0.038413  0.431350  2.006119 -0.174665   
887  1.270711 -1.572211  0.735342 -0.269675 -0.475199 -0.474326 -0.033760   
888 -0.786961  0.825209  0.735342  0.192848 -0.475199 -0.474326 -0.496733   

        alone  embarked_C  embarked_Q  embarked_S  
0   -1.229349   -0.482711   -0.307941    0.616794  
1   -1.229349    2.071634   -0.307941   -1.621287  
2    0.813439   -0.482711   -0.307941    0.616794  
3   -1.229349   -0.482711   -0.307941    0.616794  
4    0.813439   -0.482711   -0.307941    0.616794  
..        ...         ...         ...         ...  
884  0.813439   -0.482711   -0.307941    0.616794  
885  0.813439   -0.482711   -0.307941    0.616794  
886 -1.229349   -0.482711   -0.307941    0.616794  
887  0.813439    2.071634   -0.307941   -1.621287  
888  0.813439   -0.482711    3.247377   -1.621287  

[889 rows x 11 columns]

In [115]:
X=df2.drop('survived',axis=1)
y=df['survived'] # Use the unscaled 'survived' column from df

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [116]:
from sklearn.linear_model import LogisticRegression

In [117]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [118]:
y_pred=model.predict(X_test)


In [119]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [120]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

#for classification algorithm we use confusion matrix for reporting accuracy of graph
📖 Story: The Hospital Test

Imagine a doctor testing whether a patient has a disease.

There are 2 realities:

Patient HAS disease

Patient does NOT have disease

And 2 predictions:

Test says YES

Test says NO

🧩 Confusion Matrix (the full picture)
	Predicted YES	Predicted NO
Actual YES	✅ TP	❌ FN
Actual NO	❌ FP	✅ TN
🧠 Understand each term like a human
✅ TP (True Positive)

Patient has disease → test says YES
👉 Correct alarm

❌ FP (False Positive)

Patient does NOT have disease → test says YES
👉 False alarm (unnecessary panic)

❌ FN (False Negative)

Patient has disease → test says NO
👉 Dangerous miss ⚠️

✅ TN (True Negative)

Patient does NOT have disease → test says NO
👉 Correct relief
🎯 1. Accuracy — “Overall correctness”
📖 Story

Out of all patients, how many did the doctor diagnose correctly?

✅ Formula
Accuracy
=
𝑇
𝑃
+
𝑇
𝑁
𝑇
𝑃
+
𝑇
𝑁
+
𝐹
𝑃
+
𝐹
𝑁
Accuracy=
TP+TN+FP+FN
TP+TN
	​

🧠 Meaning

Simple

But dangerous for imbalanced data

📌 Example:
99 healthy, 1 sick
Model says “NO” to everyone → 99% accuracy, useless model 🤦

🎯 2. Precision — “How trustworthy YES is”
📖 Story

When the doctor says YES, how often is he actually right?

✅ Formula
Precision
=
𝑇
𝑃
𝑇
𝑃
+
𝐹
𝑃
Precision=
TP+FP
TP
	​

🧠 Meaning

Focuses on false alarms

Important when wrong YES is costly

📌 Used in:

Spam detection

Fraud detection
(You don’t want to accuse innocent people)

🎯 3. Recall — “How many actual YES we caught”
📖 Story

Out of all sick patients, how many did the doctor detect?

✅ Formula
Recall
=
𝑇
𝑃
𝑇
𝑃
+
𝐹
𝑁
Recall=
TP+FN
TP
	​

🧠 Meaning

Focuses on missed cases

Important when missing YES is dangerous

📌 Used in:

Medical diagnosis

Cancer detection
(Missing a disease is deadly)

🎯 4. F1 Score — “Balanced judge”
📖 Story

A strict teacher who says:
“You must be good at BOTH precision and recall.”

✅ Formula
F1
=
2
×
(
Precision
×
Recall
)
Precision
+
Recall
F1=
Precision+Recall
2×(Precision×Recall)
	​

🧠 Meaning

Harmonic mean

Punishes imbalance

Best single metric for imbalanced datasets

🧠 Ultra-easy memory table (EXAM GOLD)
Metric	Question it answers
Accuracy	“Overall, how often correct?”
Precision	“Can I trust YES?”
Recall	“Did I miss any YES?”
F1 Score	“Are Precision & Recall balanced?”
🔑 One-line memory trick (lock it forever)

Accuracy sees everyone
Precision checks YES quality
Recall checks missed YES

In [121]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [122]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [123]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

The confusion matrix is displayed above, where:
- The top-left value is True Negative (TN)
- The top-right value is False Positive (FP)
- The bottom-left value is False Negative (FN)
- The bottom-right value is True Positive (TP)

And the accuracy score indicates the overall correctness of the model.

In [124]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [125]:
x1=df.drop('survived',axis=1)
y1=df['survived']
X_train1,X_test1,Y_train1,Y_test1=train_test_split(x1,y1,test_size=0.2,random_state=42)


In [126]:
model2=LogisticRegression()
model2.fit(X_train1,Y_train1)

LogisticRegression()

In [127]:
Y_PREDICTION=model2.predict(X_test1)


In [128]:
accuracy_score(Y_test1,Y_PREDICTION)

0.8033707865168539

In [129]:
from sklearn.neighbors import KNeighborsClassifier

In [130]:
model3=KNeighborsClassifier(n_neighbors=5)
model3.fit(X_train,y_train)

KNeighborsClassifier()

In [131]:
y_predict22=model.predict(X_test)

In [132]:
confusion_matrix(y_test,y_predict22)

array([[90, 19],
       [16, 53]])

In [133]:
print(classification_report(y_test,y_predict22))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



https://chatgpt.com/share/6982febe-3a60-800f-b04e-3377653e7189 # NAIVE BAYES ALGORITHM

In [134]:
from sklearn.naive_bayes import GaussianNB

In [135]:
model22=GaussianNB()
model22.fit(X_train1,Y_train1)

GaussianNB()

In [136]:
y_predict22=model22.predict(X_test1)


In [137]:
y_predict22

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [138]:
confusion_matrix(y_test,y_predict22)

array([[81, 28],
       [16, 53]])

In [139]:
accuracy_score(y_test,y_predict22)

0.7528089887640449

In [140]:
from sklearn.tree import DecisionTreeClassifier

In [141]:
model=DecisionTreeClassifier(random_state=42)
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [142]:
y_predict21=model.predict(X_test)

In [143]:
y_predict21

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0])

In [144]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [145]:
accuracy_score22=accuracy_score(y_test,y_predict21)

In [146]:
confusion_matrix(y_test,y_predict21)

array([[88, 21],
       [17, 52]])

In [147]:
print(classification_report(y_test,y_predict21))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       109
           1       0.71      0.75      0.73        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178



In [148]:
print(accuracy_score22)

0.7865168539325843


#if all columns are categorical then this model will be the best model to train in decision trees

for age and fare which are continuous variables we use mean squareds error

In [149]:
from sklearn.svm import SVC
model_svm22=SVC(kernel='rbf')
model_svm22.fit(X_train,y_train)

SVC()

In [150]:
y_predict_svm22=model_svm22.predict(X_test)


In [151]:
confusion_matrix(y_test,y_predict_svm22)

array([[92, 17],
       [17, 52]])

In [152]:
accuracy_score(y_test,y_predict_svm22)

0.8089887640449438

In [153]:
print(classification_report(y_test,y_predict_svm22))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       109
           1       0.75      0.75      0.75        69

    accuracy                           0.81       178
   macro avg       0.80      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178



In [154]:
from sklearn .model_selection import cross_val_score

In [155]:
scores=cross_val_score(model3,X,y,cv=5,scoring='accuracy')

In [156]:
print(scores)

[0.78089888 0.76966292 0.8258427  0.81460674 0.80225989]


In [157]:
print(scores.mean())#avg accuracy score of model

0.7986542245921411


#grid search cv

In [158]:
param_grid = {
     'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

In [159]:
y_predict5=model2.predict(X_test1)

In [160]:
accuracy_score(Y_test1,y_predict5)


0.8033707865168539

In [161]:
from sklearn.model_selection import GridSearchCV

In [162]:
classifier= GridSearchCV(model3,param_grid,cv=10,scoring='accuracy')

In [163]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [164]:
y_predict=classifier.predict(X_test)

In [165]:
accuracy_score(y_test,y_predict)

0.7808988764044944

#random search cv

In [166]:
from sklearn.model_selection import RandomizedSearchCV

In [167]:
classifier_r= RandomizedSearchCV(model3,param_grid,n_iter=1000,cv=10,scoring='accuracy')

In [168]:
classifier_r.fit(X_train,y_train)

RandomizedSearchCV(cv=10, estimator=KNeighborsClassifier(), n_iter=1000,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9],
                                        'weights': ['uniform', 'distance']},
                   scoring='accuracy')

In [169]:
results=pd.DataFrame(classifier_r.cv_results_)

In [170]:
y_predict_r=classifier_r.predict(X_test)

In [171]:
accuracy_score(y_test,y_predict_r)

0.7808988764044944

In [172]:
results[['param_weights','param_n_neighbors','param_metric','mean_test_score'	]]

param_weights  param_n_neighbors param_metric  mean_test_score
0        uniform                  3    euclidean         0.825548
1       distance                  3    euclidean         0.810094
2        uniform                  5    euclidean         0.825587
3       distance                  5    euclidean         0.812911
4        uniform                  7    euclidean         0.822809
5       distance                  7    euclidean         0.811561
6        uniform                  9    euclidean         0.804499
7       distance                  9    euclidean         0.807336
8        uniform                  3    manhattan         0.834018
9       distance                  3    manhattan         0.814339
10       uniform                  5    manhattan         0.832668
11      distance                  5    manhattan         0.814378
12       uniform                  7    manhattan         0.831240
13      distance                  7    manhattan         0.815767
14       uniform                  9    manhattan         0.811541
15      distance                  9    manhattan         0.818603